apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuwunel.fullname" . }}
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tuwunel.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
